Update notices.json
mattermost/notices pull request #111
Opened 2020-12-08 18:45 UTC by amyblais

For v5.30 release

2020-12-08 19:08 UTC, cwarnermm approved these changes
Looks good to me! Thanks!

2020-12-08 19:09 UTC, esethna requested changes

2020-12-08 19:09 UTC, esethna commented on notices.json
> +        "description": "Mattermost server v5.30 is now available offering Incident Management out-of-the-box, a new MS Teams Meetings plugin, configuration of new administrator roles from the System
Propose:
Mattermost server v5.30 is now available offering a new MS Teams Meetings plugin, new administrator roles configurable in the System Console, and improvements to the Matterpoll plugin. [Upgrading](https://docs.mattermost.com/administration/upgrade.html) only takes a few minutes.

_______

> Incident Management out-of-the-box, 
Not really clear how this is different than the text in v5.29 "pre-installed incident management application (E20)"? Propose we just remove it?

2020-12-08 19:25 UTC, esethna submitted a review, later dismissed

2020-12-08 19:25 UTC, esethna commented
@amyblais this should only be merged after the release is available (or else we are removing the v5.29 notice)

2020-12-15 13:45 UTC, amyblais commented
@ogi-m Kind reminder to test this.

2020-12-18 18:35 UTC, amyblais commented
@ogi-m v5.30.1 has the fix for the version number.

2020-12-18 21:32 UTC, esethna commented
@amyblais I'll be out for holidays now, but please merge this when it's tested and verified

2020-12-18 21:33 UTC, esethna approved these changes

2020-12-21 21:44 UTC, ogi-m approved these changes
Tested and passed
- notice does not show up on cloud servers
- version check working

cc @amyblais

2021-01-04 13:05 UTC, merged