v5.35 Notice
mattermost/notices pull request #181
Opened 2021-05-12 13:40 UTC by amyblais

2021-05-13 18:47 UTC, esethna requested changes

2021-05-13 18:47 UTC, esethna commented on notices.json
> +        "description": "The new feature release offers shared channels, add/remove ad hoc tasks for incident collaboration playbooks, file search, and more. [Please also see the important upgrade not
@amyblais wondering if we can summarize the improvements better? Perhaps:

"Stakeholder overview and ad hoc tasks for incident collaboration" 0/5

2021-05-13 18:49 UTC, esethna approved these changes

2021-05-19 13:27 UTC, ogi-m approved these changes

2021-05-19 13:31 UTC, amyblais commented
@cpanato I'm unable to merge this because of the incomplete git.internal check. Wondering if you can help?

2021-05-19 13:31 UTC, cpanato commented
i will fix that later and give you the access as well

merging

2021-05-19 13:32 UTC, cpanato commented
@amyblais can you please make a ticket for that?

2021-05-19 13:32 UTC, merged