Desktop 4.7 Notice
mattermost/notices pull request #191
Opened 2021-06-23 15:04 UTC by amyblais

2021-06-23 20:58 UTC, esethna requested changes

2021-06-23 20:58 UTC, esethna commented on notices.json
> +        "description": "Upgrade now to access Electron BrowserView, an underlying architecture change that improves performance and offers snappier interactions (i.e., less lag), lower CPU usage, and
We can probably cut this part of the sentence: "Electron BrowserView, an underlying architecture change that "

From the end user perspective they care about what it means to them

2021-06-25 01:41 UTC, mateusz76 approved these changes

2021-06-25 01:41 UTC, mateusz76 commented on notices.json
>          "image": "https://raw.githubusercontent.com/mattermost/notices/master/images/desktop_upgrade.png",
notices.json

2021-06-25 18:12 UTC, esethna approved these changes

2021-06-28 10:52 UTC, ogi-m approved these changes

2021-08-04 12:17 UTC, merged