Unsupported server notice
mattermost/notices pull request #321
Opened 2022-11-22 19:21 UTC by amyblais

2022-11-22 19:50 UTC, ogi-m approved these changes
LGTM 👍🏻

2022-11-23 11:14 UTC, phoinixgrr requested changes

2022-11-23 11:14 UTC, phoinixgrr commented on notices.json
> +  },
JSON does not validate. 


```suggestion
  }
```

2022-11-23 13:18 UTC, amyblais commented on notices.json
> +  },
@phoinixgrr I've committed the fix.

2022-11-23 14:12 UTC, phoinixgrr approved these changes
🎖️

2022-11-23 14:15 UTC, merged